codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: no # Enable me later!
    patch: no # Enable me later!
    changes: no

comment:
  layout: "diff"
  behavior: new
  require_changes: yes
