# Job for mac

parameters:
  pool:
    vmImage: 'macOS-10.14'
  preBuild: []

jobs:
- template: job-build.yml
  parameters:
    jobName: 'Mac'
    pool: ${{ parameters.pool }}
    container: ''
    jdkVersionOption: '1.11'
    artifactName: 'Mac'
    preBuild:
    - ${{ parameters.preBuild }}
    - script: |
        mkdir build
        export JAVA_HOME=`/usr/libexec/java_home -v 11`
      displayName: 'Setup JDK'
